### ISSUE TITLE
Prijevod forme se ne prikazuje

### ISSUE THREAD

**Issue by LevelUpGit** [MonriPayments/woocommerce-monri#21]
Pozdrav, 

prijevod forme se ne prikazuje iako je odabran Bosanski jezik unutar plugina.

![Screenshot_2](https://user-images.githubusercontent.com/69863985/120987566-ffb7b100-c77d-11eb-800e-18895357da01.jpg)
 Lp

**Comment by ivanweiler** [comment]
This is solved in latest version
