### ISSUE TITLE
Billing details deprecated calls

### ISSUE THREAD

**Issue by dado-inc** [MonriPayments/woocommerce-monri#32]
Billing details, first_name, last_name, address_1, city, postcode, country, phone, email  and order_key are called incorrectly using deprecated call. Order properties should not be accessed directly.
Woocommerce get_ function should be used on each ($order->get_billing_first_name()).

**Comment by ivanweiler** [comment]
Hi @dado-inc This is solved in latest 3.0.0 version, so we're closing the issue
