### ISSUE TITLE
Problem sa novom verzijom plugina kod callback-a

### ISSUE THREAD

**Issue by LevelUpGit** [MonriPayments/woocommerce-monri#38]
Testirali smo posljednju verziju plugina i naišli smo na problem kod callback-a;

Uncaught Error: Call to a member function get_status() on bool in /var/www/vhosts/test.ba/monri.test.ba/wp-content/plugins/monri-payments/includes/callback.php:91

Order ID sadrži dodatne karaktere u pozivu: "order_number\":\"615-test1709817751\"

Koristimo testno okruženje.

**Comment by LevelUpGit** [comment]
U zadnjoj verziji isti problem, status narudžbe se ne ažurira.

**Comment by ivanweiler** [comment]
Hvala puno na inputu, promaknuo mi je issue, provjerimo i riješimo

**Comment by ivanweiler** [comment]
@LevelUpGit pozdrav, popravljeno u v.3.0.2

**Comment by LevelUpGit** [comment]
Pozdrav @ivanweiler , upravo smo testirali novu verziju, Callback je uredu, samo što narudžba ostaje u status "Procesing" iako je plaćena, 
![Screenshot_1](https://github.com/MonriPayments/woocommerce-monri/assets/69863985/4e8fcf12-8865-4450-979e-83179288eaec)

**Comment by ivanweiler** [comment]
@LevelUpGit Pozdrav, "Processing" je status koji treba biti ako je order placen, to znaci da je kupac uspjesno platio na Monri strani:
https://woocommerce.com/document/managing-orders/

(eventualno nije tako za virtual/downloadable proizvode)
