### ISSUE TITLE
Nisu dostupni načini plaćanja. 

### ISSUE THREAD

**Issue by dysk0** [MonriPayments/woocommerce-monri#48]
WooCommerce instaliran i podesen na clean instalaciji. Medjutim nakon podesavanja Monri Payment profile, ne pokazuje se u listi.

<img width="796" alt="image" src="https://github.com/MonriPayments/woocommerce-monri/assets/1282919/b3f5142f-249d-4fb0-a066-61335ce6719a">

Woocommerce:		8.8.2
Wordpress:		6.5.2
Server Info:		nginx
PHP verzija:		8.3.6

**Comment by dysk0** [comment]
Napomena: radi ukoliko se ukljuci Classic Checkout. Novi nacin rada s blokovima, ne radi.

**Comment by LevelUpGit** [comment]
Isto iskustvo, ali bez obzira na kojem tipu plaćanju.

**Comment by ivanweiler** [comment]
@dysk0 @LevelUpGit Pozdrav, molim da potvrdimo jednu stvar, da li koristite zadnju verziju modula v.3.1 i da li ste skinuli zip sa Github Releases:

https://github.com/MonriPayments/woocommerce-monri/releases/download/3.1.0/monri-payments.zip

Naime, postoji razlika izmedju release zipa i source koda na Guthubu, jer Releases zip sadrzi zbildani javascript za novi checkout, dok sam repo to nema (nije praksa da se stavlja u repo). Pa ako je moguće, skinite zip sa linka koji sam stavio, instalirajte i probajte.

Ako nije do ovoga, molim da kontaktirate Monri podršku pa ćemo pomoći.

**Comment by LevelUpGit** [comment]
@ivanweiler  Upravu ste, prilikom skidanja slučajno smo skinuli source verziju. Testirali smo ponovo sa components i sa klasičnom formom i sve radi. Lp
